CREATE TABLE CATEGORY(
ID INT IDENTITY PRIMARY KEY NOT NULL,
NAME NVARCHAR(100) NOT NULL,
UNIQUE(NAME)
)

CREATE TABLE PRODUCT(
ID INT IDENTITY PRIMARY KEY NOT NULL,
NAME NVARCHAR(100) NOT NULL,
STOCK INT NOT NULL DEFAULT(0),
PRICE INT NOT NULL,
PHOTO NVARCHAR(MAX) NOT NULL DEFAULT '',
CATEGORY_ID INT NOT NULL,
FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY
)