//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelImpl.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public int STOCK { get; set; }
        public int PRICE { get; set; }
        public string PHOTO { get; set; }
        public int CATEGORY_ID { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
    }
}
